import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import UglyLink from "@/components/shared/ugly-link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="min-h-screen mx-auto py-10 max-w-3xl">
          {children}
          <div className="mt-8 pt-8 border-t border-muted">
            <div className="flex items-center space-x-2">
              <UglyLink href="https://github.com/sayantank/react-and-chill">github</UglyLink>
            </div>
          </div>
          <Toaster />
        </main>
      </body>
    </html>
  );
}
